# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 946b0f235b7208cadaa51c4ae95139523221a86fc6733be0305241d28e43ef7bc8ab08aff4add47ace0971382f0f66e1b1d1dbbd09adc5c87543bcf8eb06f27d

test:
  secret_key_base: cc346bb034a838d350e056f4b61bdbe2e9f79f717d17b2077c26dcd544b52cee9baa9fc514188b8b41aae2beb8807682a7b63688afd188c5987c07091c0bee5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
